/* Top-bar menu. Pages are real documents now, so the only job left here is the
   narrow-screen panel: open it, close it on Escape, and close it if the window
   grows back to a width where the full bar fits. */
(function () {
  var toggle = document.querySelector(".navtoggle");
  if (!toggle) return;
  var icon = toggle.querySelector(".navicon");

  function close() {
    document.body.classList.remove("nav-open");
    toggle.setAttribute("aria-expanded", "false");
    icon.innerHTML = "&#9776;";
  }
  toggle.addEventListener("click", function () {
    var open = document.body.classList.toggle("nav-open");
    toggle.setAttribute("aria-expanded", open ? "true" : "false");
    icon.innerHTML = open ? "&#10005;" : "&#9776;";
  });
  document.addEventListener("keydown", function (e) { if (e.key === "Escape") close(); });
  /* 1184px is 74rem, the width at which site.css puts the full six-tab bar back. The two
     numbers are the same decision and have to be changed together. */
  window.addEventListener("resize", function () { if (window.innerWidth > 1184) close(); });
})();

/* The release notes filter, on /releases only.

   The page is generated by tools/build-releases.js and every release is in the HTML, newest
   first, with the latest one open. That is the whole page for a reader with scripting off,
   which is why the dropdown is styled off until this file runs: a select that submits,
   reloads a static document and changes nothing is a control that lies about what it does.

   With this running, choosing a date shows that release on its own and writes what happened
   into the status line, and the URL gains ?release=<date> so a single release can be linked
   to and shared. */
(function () {
  var form = document.querySelector(".rel-filter");
  if (!form) return;

  var select = document.getElementById("release-filter");
  var status = document.getElementById("rel-status");
  var cards = Array.prototype.slice.call(document.querySelectorAll(".rel"));

  /* Loud, not quiet. All three are emitted on every build, so a missing one means the page
     and this file have drifted apart. Skipping instead would leave a filter that silently
     does nothing, which looks exactly like a filter with nothing to filter. */
  if (!select || !status || !cards.length) {
    throw new Error(
      "The releases page is missing its filter, its status line or its release cards. " +
      "Rebuild it with tools/build-releases.js.");
  }

  var dates = cards.map(function (c) { return c.getAttribute("data-release"); });

  function labelFor(date) {
    var card = cards[dates.indexOf(date)];
    var when = card && card.querySelector("time");
    return when ? when.textContent : date;
  }

  function apply(value) {
    var latest = cards[0];
    cards.forEach(function (card) {
      var match = value === "all" || card.getAttribute("data-release") === value;
      card.hidden = !match;
      card.open = match && (value !== "all" || card === latest);
    });
    status.textContent = value === "all"
      ? "Showing all " + cards.length + " releases, newest first."
      : "Showing the release from " + labelFor(value) + ". Choose all releases to see the rest.";
  }

  function remember(value) {
    if (!window.history || !history.replaceState) return;
    var url = location.pathname +
      (value === "all" ? "" : "?release=" + encodeURIComponent(value));
    try {
      history.replaceState(null, "", url);
    } catch (e) {
      /* Refused when the page is opened from disk rather than served. The filter has already
         been applied by this point, so the only thing lost is a shareable address. */
    }
  }

  function requested() {
    var q = /[?&]release=([^&#]+)/.exec(location.search);
    if (q) return decodeURIComponent(q[1]);
    var h = /^#r-(\d{4}-\d{2}-\d{2})$/.exec(location.hash);
    return h ? h[1] : null;
  }

  function choose(value) {
    select.value = value;
    apply(value);
    remember(value);
  }

  select.addEventListener("change", function () { choose(select.value); });

  form.addEventListener("submit", function (e) {
    e.preventDefault();
    choose(select.value);
    /* Put the reader on the result. On a long page the release that survives the filter can
       otherwise be below the fold, and nothing looks like it happened. */
    var first = cards.filter(function (c) { return !c.hidden; })[0];
    if (first) first.querySelector(".rel-sum").focus();
  });

  var wanted = requested();
  if (wanted && dates.indexOf(wanted) === -1) {
    choose("all");
    status.textContent = "There is no release dated " + wanted +
      ". Showing all " + cards.length + " releases, newest first.";
  } else {
    choose(wanted || "all");
  }
})();
